<?php
define("WEBSITE_URL","http://www.sspadvantage.com/karbonn/smarantee/2");
define("SUCCESS_URL",WEBSITE_URL.'/payu/success.php');
define("FAILURE_URL",WEBSITE_URL.'/payu/failure.php');
/*define("PAYU_SALT","e5iIg1jwi8");
define("PAYU_KEY","rjQUPktU");
define("PAYU_URL","https://test.payu.in");*/
define("PAYU_SALT","qL2jVYYrvL");
define("PAYU_KEY","llRZqSU5");
define("PAYU_URL","https://secure.payu.in");
?>